name: 🛠 Build & Release App A

on:
  push:
    branches: [ app/app_a ]
    tags:
      - 'v*'
  pull_request:
    branches: [ app/app_a ]
    tags:
      - 'v*'

permissions:
  contents: write   # allow creating/updating Releases & uploading assets
  actions:  read    # allow pulling marketplace actions

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest

    steps:
      - name: 📂 Checkout code
        uses: actions/checkout@v3

      - name: 🚀 Cache pub deps
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: ${{ runner.os }}-pub-

      - name: ☕️ Setup Java (Temurin 17)
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: 🦋 Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: 🍈 Setup Melos
        uses: bluefireteam/melos-action@v3

      - name: 📥 Get dependencies
        run: |
          cd ./apps/app_a
          flutter pub get

      - name: ✅ Run tests
        run: |
          cd ./apps/app_a
          flutter test --coverage

      - name: 🏗️ Build APKs
        run: |
          cd ./apps/app_a
          flutter build apk --release --split-per-abi

      - name: 📦 Prepare artifacts
        run: |
          mkdir -p artifacts
          mv ./apps/app_a/build/app/outputs/flutter-apk/*.apk artifacts
          cd artifacts
          mv app-arm64-v8a-release.apk app_aaa-arm64-v8a-release.apk.apk
          mv app-armeabi-v7a-release.apk app_aaa-armeabi-v7a-release.apk.apk
          mv app-x86_64-release.apk app_aaa-x86_64-release.apk.apk

      - name: 🏷️ Create or update Release
        uses: ncipollo/release-action@v1.16.0
        with:
          tag:       ${{ github.ref_name }}
          name:      Release v1.2.9
          artifacts: artifacts/*.apk
          token:     ${{ secrets.GITHUB_TOKEN }}

          # Update this release, and keep the other apps’ release files unchanged.
          allowUpdates: true
          replacesArtifacts: true
          removeArtifacts: false
